"""social

Revision ID: e730ea4c71f1
Revises: 13be7e7c28f2
Create Date: 2022-11-27 18:16:38.278302

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e730ea4c71f1'
down_revision = '13be7e7c28f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
