"""social

Revision ID: e9f4adef584a
Revises: a1e65dc79adb
Create Date: 2022-11-27 18:27:46.253036

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e9f4adef584a'
down_revision = 'a1e65dc79adb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
